gtnh.settings.blowdryerTag = 0.2.2

modName = Clashweave
modId = clashweave
modGroup = com.layue13.clashweave
useModGroupForPublishing = true
autoUpdateBuildScript = false
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer
enableModernJavaSyntax = false
forceToolchainVersion = 8
enableGenericInjection = true
generateGradleTokenClass = com.layue13.clashweave.Tags
gradleTokenVersion = VERSION
usesMixins = false
usesShadowedDependencies = false
includeWellKnownRepositories = false
usesMavenPublishing = false
org.gradle.configuration-cache = true
org.gradle.parallel = true
org.gradle.workers.max = 4
org.gradle.jvmargs = -Xmx2G -Dfile.encoding=UTF-8
